// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ColorNameFinder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("input_hex")]
        public string InputHex { get; set; }

        [JsonProperty("input_rgb")]
        public Rgb InputRgb { get; set; }

        [JsonProperty("exact_match")]
        public bool ExactMatch { get; set; }

        [JsonProperty("closest_color")]
        public Closest ClosestColor { get; set; }

        [JsonProperty("closest_matches")]
        public Closest[] ClosestMatches { get; set; }

        [JsonProperty("total_named_colors")]
        public long TotalNamedColors { get; set; }
    }

    public partial class Closest
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("hex")]
        public string Hex { get; set; }

        [JsonProperty("distance")]
        public double Distance { get; set; }

        [JsonProperty("similarity")]
        public double Similarity { get; set; }

        [JsonProperty("rgb")]
        public Rgb Rgb { get; set; }
    }

    public partial class Rgb
    {
        [JsonProperty("r")]
        public long R { get; set; }

        [JsonProperty("g")]
        public long G { get; set; }

        [JsonProperty("b")]
        public long B { get; set; }
    }
}
